# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robustness Research 
email: dawnwei.song@gmail.com
locale: en-US
# theme: minimal-mistakes-jekyll  #jekyll-theme-hacker
remote_theme: mmistakes/minimal-mistakes@4.26.2 #required by github.io
description: >- # this means to ignore newlines until "baseurl:"
  Research on robust machine learning with Big data on healthcare, MRI and cryoET/cryoEM
twitter_username: dawnsongx 
github_username: dawnsong 
minimal_mistakes_skin: dark #default
search: true

# Build settings
markdown: kramdown
kramdown:
  list_indent: 2
  input: GFM #default ,  GitHub Flavored Markdown (GFM) processor
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
  # parse_block_html: true
  # parse_span_html: true
  # parse_block_text: true
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York	# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-algolia

author:
  name   : "Xiaowei Song"
  avatar : "/assets/images/xiaowei-xihu.png"
  bio    : "Robust researching on machine learning (ML) with big data of Health care, Neuroimaging, and cryoET/cryoEM. <br/>Open for collaborations: dawnwei.song (AT) gmail.com"
  links:
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=b2M-4scAAAAJ"
    - label: "restfmri.net"
      icon: "fa-solid fa-brain"
      url: "http://restfmri.net/forum/blog/1"      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dawnsong"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/dawnsongx"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dawnsong"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:    
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 200 #default is 200
      comments: true
      share: true
      related: true
      show_date: true
      show_read_time: true
      show_tags: true
      show_categories: true      
      toc: true
      toc_label: "Contents"
      toc_icon: "cloud-moon-rain" # "cog"
      toc_sticky: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true
      show_read_time: true
      show_tags: true
      show_categories: true      
      toc: true
      toc_label: "Contents"
      toc_icon: "cloud-sun-rain"
      toc_sticky: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "facebook"
  facebook:
    appid: 397576196611119 # optional
    num_posts: 5 # 5 (default)
    colorscheme: "dark" # "light" (default), "dark"

lunr:
  search_within_pages: true
  search_full_content: false # true might impact page loading performance

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-BYFL6HDBJH"
    anonymize_ip: false # default  